In [262]:
import torch
import torch.nn
import torch.nn.functional as F

# nn.Module

In [55]:
class BB(nn.Module):
    def __init__(self):
        super(BB, self).__init__()
        
    def forward(self, x): 
        return torch.cat((x,x))

In [128]:
class H(nn.Module):
    def __init__(self):
        super(H, self).__init__()
        self.w = torch.randn((10,2), requires_grad=True)
    def forward(self, x):
        return torch.flatten(torch.matmul(x, self.w))

In [129]:
bb = BB()
h  = H()

In [130]:
x = torch.randn((1, 10))

In [131]:
a1 = bb(x)

In [132]:
a2 = h(a1)

In [133]:
a2.shape

torch.Size([4])

In [134]:
def loss(y, y_hat): return torch.sum((y-y_hat)**2)

In [135]:
l = loss(a2, torch.randn((4))) 

In [136]:
l.backward()

In [139]:
h.w.grad

tensor([[  8.2700,  -0.8345],
        [-14.7763,   1.4909],
        [  7.9935,  -0.8066],
        [ -3.3582,   0.3388],
        [ -7.9766,   0.8048],
        [  5.5956,  -0.5646],
        [  2.3606,  -0.2382],
        [ 13.1206,  -1.3239],
        [ 13.4634,  -1.3585],
        [ 12.2386,  -1.2349]])

# * Output

In [620]:
class C3(nn.Module):
    def __init__(self):
        super(C3, self).__init__()
        self.l = nn.Linear(512, 10)
    def forward(self, x):
        x = self.l(x)
        a1 = F.softmax(x[:4], dim=0)
        a2 = F.softmax(x[4:], dim=0)
        return torch.cat((a1,a2))

In [621]:
c3 = C3()

In [622]:
y = c3(torch.randn(512))
y

tensor([0.2169, 0.0682, 0.6247, 0.0902, 0.1864, 0.0915, 0.3552, 0.1695, 0.0571,
        0.1402], grad_fn=<CatBackward>)

# Custom Loss

### MSE + CE Loss

In [612]:
n_c = 5
n_b = 4

In [613]:
i = F.softmax(torch.randn((n_b,n_c)), dim=1)
i

tensor([[0.2208, 0.3098, 0.2643, 0.0511, 0.1540],
        [0.4999, 0.0817, 0.1952, 0.1484, 0.0747],
        [0.4241, 0.1652, 0.1107, 0.0211, 0.2789],
        [0.7595, 0.0658, 0.0388, 0.1123, 0.0237]])

In [614]:
t = torch.Tensor([1, 2, 0, 3]).type(torch.long)
t

tensor([1, 2, 0, 3])

In [615]:
def loss(i, t):
    i1 = i[:3,:]
    i2 = i[3:,:]
    t1 = t[:3]
    t2 = t[3:]
    ce  = F.cross_entropy(i1, t1)
    tt2 = torch.zeros(5)
    tt2[t2] = 1
    i2 = torch.squeeze(i2)
    print(tt2.shape)
    print(i2.shape)
    mse = F.mse_loss(tt2, i2)
    return ce + mse

In [616]:
l = loss(i, t)

torch.Size([5])
torch.Size([5])


In [609]:
l

tensor(2.0251)