In [55]:
import torch
from torch.utils.data import Dataset, DataLoader, RandomSampler

In [91]:
class D(Dataset):
    def __init__(self, r):
        self.r = r
        self.samples = torch.randn((r, 4))
    def __len__(self): return self.r
    def __getitem__(self, i):
        y = self.samples[i][0]
        x = self.samples[i][1:]
        return x, y

In [92]:
ds = D(12)

In [93]:
dl = DataLoader(ds, batch_size=3, shuffle=True)

In [97]:
for x, y in dl:
    print(x)
    print(y)

tensor([[-0.4351,  1.3758, -0.4686],
        [ 0.4742, -0.3834, -1.2227],
        [-1.9594, -0.2238,  1.2106]])
tensor([ 1.5823, -0.4334, -1.2179])
tensor([[ 0.4187, -0.8748, -1.4204],
        [-1.6338, -0.0729, -0.3740],
        [-0.0270, -0.1134,  0.8010]])
tensor([ 0.3442, -0.1989,  0.6043])
tensor([[ 0.9224, -0.5593, -1.5377],
        [-0.6700,  0.7551, -0.7012],
        [-0.2725, -1.8981,  0.2129]])
tensor([ 0.5454, -0.0087,  1.7695])
tensor([[-1.0871,  0.3957, -0.4559],
        [ 1.3982,  1.5853,  0.0742],
        [-0.9206, -0.3769,  0.9066]])
tensor([-0.2117, -1.1051,  1.2205])
